from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from typing import Literal

EpistemicStatus = Literal["OBSERVED", "CALCULATED", "INFERRED", "UNKNOWN"]
ImplementationStatus = Literal["ACTIVE", "PARTIAL", "CONTRACT", "LICENSED_INTERFACE"]
DependencyMode = Literal["ALL", "ANY"]

FACTOR_REGISTRY_VERSION = "gold-reference-book-2026-07-v8"


@dataclass(frozen=True, slots=True)
class FactorDefinition:
    code: str
    name: str
    domain: str
    layer: int | None
    epistemic_status: EpistemicStatus
    implementation_status: ImplementationStatus
    phase1_required: bool
    source_class: str
    series_codes: tuple[str, ...] = ()
    dependencies: tuple[str, ...] = ()
    dependency_mode: DependencyMode = "ALL"
    freshness_seconds: int | None = None
    note: str = ""


def _factor(
    code: str,
    name: str,
    domain: str,
    layer: int | None,
    epistemic_status: EpistemicStatus,
    implementation_status: ImplementationStatus,
    phase1_required: bool,
    source_class: str,
    *,
    series_codes: tuple[str, ...] = (),
    dependencies: tuple[str, ...] = (),
    dependency_mode: DependencyMode = "ALL",
    freshness_seconds: int | None = None,
    note: str = "",
) -> FactorDefinition:
    return FactorDefinition(
        code=code,
        name=name,
        domain=domain,
        layer=layer,
        epistemic_status=epistemic_status,
        implementation_status=implementation_status,
        phase1_required=phase1_required,
        source_class=source_class,
        series_codes=series_codes,
        dependencies=dependencies,
        dependency_mode=dependency_mode,
        freshness_seconds=freshness_seconds,
        note=note,
    )


# This is deliberately broader than the currently connected feeds. A factor remains
# visible as UNKNOWN until its evidence contract is satisfied; absence never removes
# it from the product's scope.
FACTOR_REGISTRY: tuple[FactorDefinition, ...] = (
    # Market mechanics, liquidity and structure from Parts I and IV.
    _factor(
        "XAUUSD_PRICE",
        "XAUUSD spot/CFD price",
        "MARKET_MECHANICS",
        None,
        "OBSERVED",
        "ACTIVE",
        True,
        "BROKER_OR_LICENSED",
        freshness_seconds=300,
    ),
    _factor(
        "COMEX_GOLD_PRICE",
        "COMEX gold futures price",
        "MARKET_MECHANICS",
        None,
        "OBSERVED",
        "LICENSED_INTERFACE",
        False,
        "LICENSED_EXCHANGE",
    ),
    _factor(
        "BID_ASK_SPREAD",
        "Bid/ask spread",
        "LIQUIDITY",
        5,
        "OBSERVED",
        "ACTIVE",
        True,
        "BROKER_OR_LICENSED",
        freshness_seconds=60,
        note=(
            "Observed IC Markets MT5 bar spread is stored in points and price units. "
            "It is a broker quote, not a centralized COMEX spread."
        ),
    ),
    _factor(
        "TRADED_VOLUME",
        "Futures or broker volume",
        "LIQUIDITY",
        5,
        "OBSERVED",
        "PARTIAL",
        True,
        "BROKER_OR_LICENSED",
        freshness_seconds=300,
        note="MT5 tick volume is not represented as centralized COMEX volume.",
    ),
    _factor(
        "LIQUIDITY_DEPTH",
        "Quoted market depth",
        "LIQUIDITY",
        5,
        "OBSERVED",
        "LICENSED_INTERFACE",
        False,
        "LICENSED_MARKET_DEPTH",
    ),
    _factor(
        "LIQUIDITY_RESILIENCE",
        "Liquidity refill/resilience",
        "LIQUIDITY",
        5,
        "CALCULATED",
        "LICENSED_INTERFACE",
        False,
        "LICENSED_MARKET_DEPTH",
        dependencies=("LIQUIDITY_DEPTH",),
    ),
    _factor(
        "MARKET_IMPACT_PROXY",
        "Market-impact proxy",
        "LIQUIDITY",
        5,
        "INFERRED",
        "CONTRACT",
        False,
        "CALCULATED_FROM_QUOTES_AND_VOLUME",
        dependencies=("BID_ASK_SPREAD", "TRADED_VOLUME"),
    ),
    _factor(
        "MULTITIMEFRAME_STRUCTURE",
        "Multi-timeframe market structure",
        "MARKET_STRUCTURE",
        7,
        "CALCULATED",
        "ACTIVE",
        True,
        "PRICE_DERIVED",
        dependencies=("XAUUSD_PRICE",),
        note=(
            "Deterministic confirmed-pivot structure runs from one minute through "
            "daily without filling missing source bars."
        ),
    ),
    _factor(
        "ACCEPTANCE_REJECTION",
        "Acceptance, rejection and failed breakout",
        "MARKET_STRUCTURE",
        7,
        "INFERRED",
        "ACTIVE",
        True,
        "PRICE_DERIVED",
        dependencies=("XAUUSD_PRICE",),
    ),
    _factor(
        "COMPRESSION_EXPANSION",
        "Compression, expansion and displacement",
        "MARKET_STRUCTURE",
        7,
        "CALCULATED",
        "ACTIVE",
        True,
        "PRICE_DERIVED",
        dependencies=("XAUUSD_PRICE",),
    ),
    _factor(
        "ABSORPTION_PROXY",
        "Absorption proxy",
        "MARKET_STRUCTURE",
        7,
        "INFERRED",
        "CONTRACT",
        False,
        "VOLUME_AND_PRICE_DERIVED",
        dependencies=("XAUUSD_PRICE", "TRADED_VOLUME"),
    ),
    # Layer 1: market regime.
    _factor(
        "CPI_HEADLINE",
        "Headline CPI",
        "INFLATION",
        1,
        "OBSERVED",
        "PARTIAL",
        True,
        "BLS_OR_ALFRED_VINTAGE",
        series_codes=("US_CPI_HEADLINE",),
    ),
    _factor(
        "CPI_CORE",
        "Core CPI",
        "INFLATION",
        1,
        "OBSERVED",
        "PARTIAL",
        True,
        "BLS_OR_ALFRED_VINTAGE",
        series_codes=("US_CPI_CORE",),
    ),
    _factor(
        "PCE_HEADLINE",
        "Headline PCE",
        "INFLATION",
        1,
        "OBSERVED",
        "PARTIAL",
        True,
        "BEA_OR_ALFRED_VINTAGE",
        series_codes=("US_PCE_HEADLINE",),
    ),
    _factor(
        "PCE_CORE",
        "Core PCE",
        "INFLATION",
        1,
        "OBSERVED",
        "PARTIAL",
        True,
        "BEA_OR_ALFRED_VINTAGE",
        series_codes=("US_PCE_CORE",),
    ),
    _factor(
        "GDP_REAL",
        "Real GDP growth",
        "GROWTH",
        1,
        "OBSERVED",
        "PARTIAL",
        True,
        "BEA_OR_ALFRED_VINTAGE",
        series_codes=("US_REAL_GDP",),
    ),
    _factor(
        "RETAIL_SALES",
        "Retail sales",
        "GROWTH",
        1,
        "OBSERVED",
        "PARTIAL",
        True,
        "CENSUS_OR_ALFRED_VINTAGE",
        series_codes=("US_RETAIL_SALES",),
    ),
    _factor(
        "NONFARM_PAYROLLS",
        "Nonfarm payrolls",
        "LABOUR",
        1,
        "OBSERVED",
        "PARTIAL",
        True,
        "BLS_OR_ALFRED_VINTAGE",
        series_codes=("US_NONFARM_PAYROLLS",),
    ),
    _factor(
        "UNEMPLOYMENT_RATE",
        "Unemployment rate",
        "LABOUR",
        1,
        "OBSERVED",
        "PARTIAL",
        True,
        "BLS_OR_ALFRED_VINTAGE",
        series_codes=("US_UNEMPLOYMENT_RATE",),
    ),
    _factor(
        "WAGE_GROWTH",
        "Average hourly earnings",
        "LABOUR",
        1,
        "OBSERVED",
        "PARTIAL",
        True,
        "BLS_OR_ALFRED_VINTAGE",
        series_codes=("US_AVERAGE_HOURLY_EARNINGS",),
    ),
    _factor(
        "JOBLESS_CLAIMS",
        "Initial jobless claims",
        "LABOUR",
        1,
        "OBSERVED",
        "PARTIAL",
        True,
        "DOL_OR_ALFRED_VINTAGE",
        series_codes=("US_INITIAL_JOBLESS_CLAIMS",),
    ),
    _factor(
        "FED_POLICY_RATE",
        "Effective federal funds rate",
        "POLICY",
        1,
        "OBSERVED",
        "ACTIVE",
        True,
        "FEDERAL_RESERVE_PUBLIC",
        series_codes=("US_FED_FUNDS_EFFECTIVE",),
        freshness_seconds=172_800,
    ),
    _factor(
        "FED_SEP_PROJECTIONS",
        "Federal Reserve economic projections and dot plot",
        "POLICY",
        1,
        "OBSERVED",
        "CONTRACT",
        False,
        "FEDERAL_RESERVE_PUBLIC_MANUAL",
    ),
    _factor(
        "TREASURY_2Y",
        "2-year Treasury yield",
        "RATES",
        1,
        "OBSERVED",
        "ACTIVE",
        True,
        "FEDERAL_RESERVE_PUBLIC",
        series_codes=("US_TREASURY_2Y",),
        freshness_seconds=172_800,
    ),
    _factor(
        "TREASURY_10Y",
        "10-year nominal Treasury yield",
        "RATES",
        1,
        "OBSERVED",
        "ACTIVE",
        True,
        "FEDERAL_RESERVE_PUBLIC",
        series_codes=("US_TREASURY_10Y",),
        freshness_seconds=172_800,
    ),
    _factor(
        "REAL_YIELD_10Y",
        "10-year TIPS real yield",
        "RATES",
        1,
        "OBSERVED",
        "ACTIVE",
        True,
        "FEDERAL_RESERVE_PUBLIC",
        series_codes=("US_REAL_YIELD_10Y",),
        freshness_seconds=172_800,
    ),
    _factor(
        "BREAKEVEN_10Y",
        "10-year breakeven inflation",
        "RATES",
        1,
        "OBSERVED",
        "ACTIVE",
        True,
        "FEDERAL_RESERVE_PUBLIC",
        series_codes=("US_BREAKEVEN_10Y",),
        freshness_seconds=172_800,
    ),
    _factor(
        "YIELD_CURVE_2S10S",
        "2s10s yield-curve slope",
        "RATES",
        1,
        "CALCULATED",
        "ACTIVE",
        True,
        "CALCULATED",
        dependencies=("TREASURY_2Y", "TREASURY_10Y"),
    ),
    _factor(
        "USD_BROAD",
        "Nominal broad US dollar index",
        "DOLLAR",
        1,
        "OBSERVED",
        "ACTIVE",
        True,
        "FEDERAL_RESERVE_PUBLIC",
        series_codes=("USD_BROAD_NOMINAL",),
        freshness_seconds=259_200,
    ),
    _factor(
        "EQUITY_RISK_SENTIMENT",
        "Equity risk sentiment",
        "RISK",
        1,
        "OBSERVED",
        "PARTIAL",
        True,
        "LICENSED_OR_BROKER",
        series_codes=("US_EQUITY_PROXY",),
    ),
    _factor(
        "FINANCIAL_STRESS",
        "Financial or liquidity stress",
        "RISK",
        1,
        "CALCULATED",
        "PARTIAL",
        False,
        "PUBLIC_AND_LICENSED_COMPOSITE",
        series_codes=("US_FINANCIAL_STRESS",),
    ),
    _factor(
        "MARKET_REGIME",
        "Growth-inflation-policy regime",
        "REGIME",
        1,
        "INFERRED",
        "PARTIAL",
        True,
        "RULE_ENGINE",
        dependencies=(
            "CPI_HEADLINE",
            "CPI_CORE",
            "PCE_CORE",
            "GDP_REAL",
            "NONFARM_PAYROLLS",
            "UNEMPLOYMENT_RATE",
            "FED_POLICY_RATE",
            "TREASURY_2Y",
            "REAL_YIELD_10Y",
            "USD_BROAD",
        ),
    ),
    # Layer 2: expectations and pricing.
    _factor(
        "ECONOMIC_CONSENSUS",
        "Point-in-time economic consensus",
        "EXPECTATIONS",
        2,
        "OBSERVED",
        "PARTIAL",
        True,
        "MANUAL_OR_LICENSED",
    ),
    _factor(
        "ACTUAL_VS_FORECAST",
        "Actual versus forecast surprise",
        "EXPECTATIONS",
        2,
        "CALCULATED",
        "PARTIAL",
        True,
        "EVENT_DERIVED",
        dependencies=("ECONOMIC_CONSENSUS",),
    ),
    _factor(
        "ACTUAL_VS_PREVIOUS",
        "Actual versus previous release",
        "EXPECTATIONS",
        2,
        "CALCULATED",
        "PARTIAL",
        True,
        "EVENT_DERIVED",
    ),
    _factor(
        "RELEASE_REVISIONS",
        "Economic release revisions",
        "EXPECTATIONS",
        2,
        "OBSERVED",
        "PARTIAL",
        True,
        "OFFICIAL_RELEASE_VINTAGE",
    ),
    _factor(
        "RELEASE_COMPOSITION",
        "Release component interpretation",
        "EXPECTATIONS",
        2,
        "INFERRED",
        "CONTRACT",
        True,
        "RULE_ENGINE",
    ),
    _factor(
        "FED_NEXT_MEETING_PROBABILITY",
        "Next-meeting Fed probabilities",
        "EXPECTATIONS",
        2,
        "OBSERVED",
        "PARTIAL",
        True,
        "MANUAL_OR_LICENSED_FUTURES",
    ),
    _factor(
        "FED_QUARTERLY_SOFR_EXPECTATIONS",
        "Quarterly SOFR options-implied distributions",
        "EXPECTATIONS",
        2,
        "OBSERVED",
        "ACTIVE",
        True,
        "ATLANTA_FED_PUBLIC_RESEARCH",
        note=(
            "Real quarterly average SOFR distributions; not exact FOMC meeting "
            "probabilities and subject to the source workbook licence."
        ),
    ),
    _factor(
        "FED_FIRST_MOVE_TIMING",
        "Timing of first expected Fed move",
        "EXPECTATIONS",
        2,
        "CALCULATED",
        "PARTIAL",
        True,
        "POLICY_PATH_DERIVED",
        dependencies=("FED_NEXT_MEETING_PROBABILITY",),
        note=(
            "Requires meeting-level probabilities. Quarterly SOFR distributions "
            "are too coarse to identify the first FOMC move."
        ),
    ),
    _factor(
        "FED_TOTAL_EASING_TIGHTENING",
        "Total expected easing or tightening",
        "EXPECTATIONS",
        2,
        "CALCULATED",
        "PARTIAL",
        True,
        "POLICY_PATH_DERIVED",
        dependencies=(
            "FED_NEXT_MEETING_PROBABILITY",
            "FED_QUARTERLY_SOFR_EXPECTATIONS",
        ),
        dependency_mode="ANY",
    ),
    _factor(
        "FED_TERMINAL_DESTINATION",
        "Expected policy-rate destination",
        "EXPECTATIONS",
        2,
        "CALCULATED",
        "PARTIAL",
        True,
        "POLICY_PATH_DERIVED",
        dependencies=(
            "FED_NEXT_MEETING_PROBABILITY",
            "FED_QUARTERLY_SOFR_EXPECTATIONS",
        ),
        dependency_mode="ANY",
    ),
    _factor(
        "FOMC_GUIDANCE_PROJECTIONS",
        "FOMC statement, press conference, guidance and projections",
        "EXPECTATIONS",
        2,
        "INFERRED",
        "CONTRACT",
        True,
        "FEDERAL_RESERVE_OFFICIAL",
        dependencies=("SCHEDULED_EVENT_CALENDAR",),
        note="Tone must be rule-derived from captured official text and structured projections.",
    ),
    _factor(
        "FED_PATH_REPRICING",
        "Hawkish or dovish full-path repricing",
        "EXPECTATIONS",
        2,
        "CALCULATED",
        "PARTIAL",
        True,
        "POLICY_PATH_DERIVED",
        dependencies=(
            "FED_NEXT_MEETING_PROBABILITY",
            "FED_QUARTERLY_SOFR_EXPECTATIONS",
        ),
        dependency_mode="ANY",
    ),
    # Layer 3: positioning and institutional behaviour.
    _factor(
        "COT_MANAGED_MONEY_LONG",
        "COT managed-money longs",
        "POSITIONING",
        3,
        "OBSERVED",
        "ACTIVE",
        True,
        "CFTC_PUBLIC",
        freshness_seconds=864_000,
    ),
    _factor(
        "COT_MANAGED_MONEY_SHORT",
        "COT managed-money shorts",
        "POSITIONING",
        3,
        "OBSERVED",
        "ACTIVE",
        True,
        "CFTC_PUBLIC",
        freshness_seconds=864_000,
    ),
    _factor(
        "COT_MANAGED_MONEY_NET",
        "COT managed-money net position",
        "POSITIONING",
        3,
        "CALCULATED",
        "ACTIVE",
        True,
        "CFTC_PUBLIC",
        dependencies=("COT_MANAGED_MONEY_LONG", "COT_MANAGED_MONEY_SHORT"),
    ),
    _factor(
        "COT_POSITIONING_PERCENTILE",
        "Historical COT positioning percentile",
        "POSITIONING",
        3,
        "CALCULATED",
        "ACTIVE",
        True,
        "CFTC_PUBLIC",
        dependencies=("COT_MANAGED_MONEY_NET",),
    ),
    _factor(
        "COT_PRODUCER_HEDGING",
        "Producer and commercial hedging",
        "POSITIONING",
        3,
        "OBSERVED",
        "ACTIVE",
        True,
        "CFTC_PUBLIC",
        freshness_seconds=864_000,
    ),
    _factor(
        "COMEX_OPEN_INTEREST",
        "COMEX gold open interest",
        "POSITIONING",
        3,
        "OBSERVED",
        "ACTIVE",
        True,
        "CFTC_PUBLIC_WEEKLY_AND_LICENSED_DAILY",
        freshness_seconds=864_000,
    ),
    _factor(
        "PRICE_OPEN_INTEREST_FLOW",
        "Price/open-interest participation inference",
        "POSITIONING",
        3,
        "INFERRED",
        "PARTIAL",
        True,
        "RULE_ENGINE",
        dependencies=("XAUUSD_PRICE", "COMEX_OPEN_INTEREST"),
    ),
    _factor(
        "ETF_HOLDINGS_FLOWS",
        "Gold ETF holdings and flows",
        "POSITIONING",
        3,
        "OBSERVED",
        "LICENSED_INTERFACE",
        False,
        "MANUAL_OR_LICENSED",
    ),
    _factor(
        "CENTRAL_BANK_DEMAND",
        "Central-bank gold demand",
        "POSITIONING",
        3,
        "OBSERVED",
        "LICENSED_INTERFACE",
        False,
        "MANUAL_OR_LICENSED",
    ),
    _factor(
        "OPTIONS_STRIKES_EXPIRIES",
        "Gold options strikes and expiries",
        "POSITIONING",
        3,
        "OBSERVED",
        "LICENSED_INTERFACE",
        False,
        "LICENSED_OPTIONS",
    ),
    _factor(
        "OPTIONS_IMPLIED_VOLATILITY",
        "Gold options implied volatility",
        "POSITIONING",
        3,
        "OBSERVED",
        "LICENSED_INTERFACE",
        False,
        "LICENSED_OPTIONS",
    ),
    _factor(
        "OPTIONS_CALL_PUT_OPEN_INTEREST",
        "Gold option call/put open interest by strike and expiry",
        "POSITIONING",
        3,
        "OBSERVED",
        "LICENSED_INTERFACE",
        False,
        "LICENSED_OPTIONS",
    ),
    _factor(
        "OPTIONS_DELTA_EXPOSURE",
        "Gold option delta exposure",
        "POSITIONING",
        3,
        "CALCULATED",
        "LICENSED_INTERFACE",
        False,
        "LICENSED_OPTIONS_AND_MODEL",
        dependencies=("OPTIONS_CALL_PUT_OPEN_INTEREST", "OPTIONS_IMPLIED_VOLATILITY"),
    ),
    _factor(
        "DEALER_GAMMA_ESTIMATE",
        "Dealer gamma estimate",
        "POSITIONING",
        3,
        "INFERRED",
        "LICENSED_INTERFACE",
        False,
        "LICENSED_OPTIONS_AND_MODEL",
        dependencies=(
            "OPTIONS_STRIKES_EXPIRIES",
            "OPTIONS_IMPLIED_VOLATILITY",
            "OPTIONS_CALL_PUT_OPEN_INTEREST",
        ),
    ),
    _factor(
        "FAST_SLOW_MONEY_DIVERGENCE",
        "Fast-money versus slow-money divergence",
        "POSITIONING",
        3,
        "INFERRED",
        "LICENSED_INTERFACE",
        False,
        "RULE_ENGINE",
        dependencies=("COT_MANAGED_MONEY_NET", "ETF_HOLDINGS_FLOWS", "CENTRAL_BANK_DEMAND"),
    ),
    # Layer 4: catalysts and event risk.
    _factor(
        "SCHEDULED_EVENT_CALENDAR",
        "Scheduled economic and policy calendar",
        "CATALYSTS",
        4,
        "OBSERVED",
        "PARTIAL",
        True,
        "OFFICIAL_AND_MANUAL",
    ),
    _factor(
        "UNSCHEDULED_EVENT_METADATA",
        "Unscheduled geopolitical and financial events",
        "CATALYSTS",
        4,
        "OBSERVED",
        "LICENSED_INTERFACE",
        False,
        "LICENSED_NEWS_OR_MANUAL",
    ),
    _factor(
        "REACTION_FUNCTION",
        "Current market reaction function",
        "CATALYSTS",
        4,
        "INFERRED",
        "PARTIAL",
        True,
        "RULE_ENGINE",
        dependencies=("MARKET_REGIME",),
    ),
    _factor(
        "EVENT_IMPACT_SCORE",
        "Event impact score",
        "CATALYSTS",
        4,
        "CALCULATED",
        "ACTIVE",
        True,
        "RULE_ENGINE",
        dependencies=(
            "ACTUAL_VS_FORECAST",
            "COT_POSITIONING_PERCENTILE",
            "BID_ASK_SPREAD",
            "REACTION_FUNCTION",
        ),
    ),
    _factor(
        "EVENT_REACTION_HORIZONS",
        "1m/5m/15m/1h/4h/daily event reactions",
        "CATALYSTS",
        4,
        "CALCULATED",
        "ACTIVE",
        True,
        "EVENT_STUDY",
        dependencies=("SCHEDULED_EVENT_CALENDAR", "XAUUSD_PRICE"),
    ),
    _factor(
        "EVENT_MFE_MAE",
        "Event maximum favourable/adverse excursion",
        "CATALYSTS",
        4,
        "CALCULATED",
        "PARTIAL",
        True,
        "EVENT_STUDY",
        dependencies=("EVENT_REACTION_HORIZONS",),
    ),
    _factor(
        "FIRST_MOVE_HOLD_REVERSAL",
        "First-move continuation or reversal",
        "CATALYSTS",
        4,
        "INFERRED",
        "PARTIAL",
        True,
        "EVENT_STUDY",
        dependencies=("EVENT_REACTION_HORIZONS",),
    ),
    _factor(
        "TREASURY_AUCTION_CALENDAR",
        "Treasury auction calendar and competitive bid closes",
        "CATALYSTS",
        4,
        "OBSERVED",
        "ACTIVE",
        True,
        "US_TREASURY_FISCAL_DATA",
        note=(
            "Exact auction close is observed in Eastern Time. Historical "
            "availability is conservatively the end of the published "
            "announcement date because the source omits its release time."
        ),
    ),
    _factor(
        "FED_COMMUNICATIONS_RELEASED",
        "Released Fed speeches and monetary-policy communications",
        "CATALYSTS",
        4,
        "OBSERVED",
        "ACTIVE",
        True,
        "FEDERAL_RESERVE_RSS",
        note=(
            "RSS pubDate identifies when a communication was published. Metadata "
            "does not infer hawkish or dovish tone."
        ),
    ),
    _factor(
        "FED_SPEECH_CALENDAR",
        "Forward Fed speech and testimony calendar",
        "CATALYSTS",
        4,
        "OBSERVED",
        "CONTRACT",
        True,
        "OFFICIAL_CALENDAR_OR_MANUAL",
        note=(
            "Federal Reserve RSS is a released-item feed, not a forward calendar. "
            "Future speech timing stays UNKNOWN until a timestamped calendar is loaded."
        ),
    ),
    # Layer 5: sessions and liquidity.
    _factor(
        "ASIA_SESSION",
        "Asian session",
        "SESSIONS",
        5,
        "CALCULATED",
        "ACTIVE",
        True,
        "IANA_TIMEZONE",
        dependencies=("XAUUSD_PRICE",),
    ),
    _factor(
        "LONDON_SESSION",
        "London session",
        "SESSIONS",
        5,
        "CALCULATED",
        "ACTIVE",
        True,
        "IANA_TIMEZONE",
        dependencies=("XAUUSD_PRICE",),
    ),
    _factor(
        "NEW_YORK_SESSION",
        "New York session",
        "SESSIONS",
        5,
        "CALCULATED",
        "ACTIVE",
        True,
        "IANA_TIMEZONE",
        dependencies=("XAUUSD_PRICE",),
    ),
    _factor(
        "LONDON_NEW_YORK_OVERLAP",
        "London-New York overlap",
        "SESSIONS",
        5,
        "CALCULATED",
        "ACTIVE",
        True,
        "IANA_TIMEZONE",
        dependencies=("XAUUSD_PRICE",),
    ),
    _factor(
        "DAILY_ROLLOVER",
        "Daily rollover window",
        "SESSIONS",
        5,
        "CALCULATED",
        "ACTIVE",
        True,
        "BROKER_SESSION_TEMPLATE",
        dependencies=("XAUUSD_PRICE",),
    ),
    _factor(
        "LBMA_BENCHMARK_WINDOWS",
        "LBMA AM and PM benchmark windows",
        "SESSIONS",
        5,
        "CALCULATED",
        "ACTIVE",
        True,
        "IANA_TIMEZONE",
    ),
    _factor(
        "SESSION_RANGE_HANDOVER",
        "Session ranges and handover confirmation",
        "SESSIONS",
        5,
        "CALCULATED",
        "ACTIVE",
        True,
        "PRICE_DERIVED",
        dependencies=("XAUUSD_PRICE",),
    ),
    _factor(
        "SESSION_CLOSE_SQUARING",
        "Session-close position-squaring window",
        "SESSIONS",
        5,
        "INFERRED",
        "ACTIVE",
        True,
        "PRICE_AND_TIME_DERIVED",
        dependencies=("XAUUSD_PRICE",),
    ),
    _factor(
        "ABNORMAL_LIQUIDITY",
        "Abnormal spread and volatility conditions",
        "SESSIONS",
        5,
        "CALCULATED",
        "ACTIVE",
        True,
        "PRICE_AND_SPREAD_DERIVED",
        dependencies=("XAUUSD_PRICE", "BID_ASK_SPREAD"),
    ),
    # Layer 6: cross-market confirmation.
    _factor(
        "CROSSMARKET_GOLD_RATES_USD",
        "Gold, rates and dollar synchronization",
        "CROSS_MARKET",
        6,
        "CALCULATED",
        "ACTIVE",
        True,
        "POINT_IN_TIME_ALIGNMENT",
        dependencies=("XAUUSD_PRICE", "TREASURY_2Y", "REAL_YIELD_10Y", "USD_BROAD"),
    ),
    _factor(
        "NOMINAL_REAL_BREAKEVEN_DECOMPOSITION",
        "Nominal-yield decomposition",
        "CROSS_MARKET",
        6,
        "CALCULATED",
        "ACTIVE",
        True,
        "RULE_ENGINE",
        dependencies=("TREASURY_10Y", "REAL_YIELD_10Y", "BREAKEVEN_10Y"),
    ),
    _factor(
        "VOLATILITY_INDEX",
        "Equity volatility index",
        "CROSS_MARKET",
        6,
        "OBSERVED",
        "PARTIAL",
        True,
        "LICENSED_OR_BROKER",
        series_codes=("US_VOLATILITY_INDEX",),
    ),
    _factor(
        "SILVER_CONFIRMATION",
        "Silver confirmation",
        "CROSS_MARKET",
        6,
        "OBSERVED",
        "LICENSED_INTERFACE",
        False,
        "LICENSED_OR_BROKER",
        series_codes=("XAGUSD_PRICE",),
    ),
    _factor(
        "SAFE_HAVEN_DIVERGENCE",
        "Safe-haven and gold-dollar divergence",
        "CROSS_MARKET",
        6,
        "INFERRED",
        "CONTRACT",
        True,
        "RULE_ENGINE",
        dependencies=("XAUUSD_PRICE", "USD_BROAD", "EQUITY_RISK_SENTIMENT"),
    ),
    _factor(
        "CROSSMARKET_CONFIRMATION_STATE",
        "Cross-market confirmation state",
        "CROSS_MARKET",
        6,
        "INFERRED",
        "PARTIAL",
        True,
        "RULE_ENGINE",
        dependencies=("CROSSMARKET_GOLD_RATES_USD",),
    ),
    # Layer 7: execution and risk.
    _factor(
        "FUNDAMENTAL_DIRECTIONAL_BIAS",
        "Fundamental directional bias",
        "EXECUTION_RISK",
        7,
        "INFERRED",
        "PARTIAL",
        True,
        "SEVEN_LAYER_SCORE",
        dependencies=("MARKET_REGIME", "FED_PATH_REPRICING", "COT_MANAGED_MONEY_NET"),
    ),
    _factor(
        "MECHANICAL_TRIGGER",
        "Mechanical entry trigger",
        "EXECUTION_RISK",
        7,
        "CALCULATED",
        "PARTIAL",
        True,
        "MARKET_STRUCTURE",
        dependencies=("MULTITIMEFRAME_STRUCTURE", "ACCEPTANCE_REJECTION"),
    ),
    _factor(
        "PRICE_INVALIDATION",
        "Price-structure invalidation",
        "EXECUTION_RISK",
        7,
        "CALCULATED",
        "PARTIAL",
        True,
        "MARKET_STRUCTURE",
        dependencies=("MULTITIMEFRAME_STRUCTURE",),
    ),
    _factor(
        "FUNDAMENTAL_INVALIDATION",
        "Fundamental invalidation",
        "EXECUTION_RISK",
        7,
        "INFERRED",
        "ACTIVE",
        True,
        "SEVEN_LAYER_SCORE",
        dependencies=("FUNDAMENTAL_DIRECTIONAL_BIAS",),
    ),
    _factor(
        "LOGICAL_STOP_DISTANCE",
        "Logical structure-based stop distance",
        "EXECUTION_RISK",
        7,
        "CALCULATED",
        "ACTIVE",
        True,
        "RISK_ENGINE",
        dependencies=("PRICE_INVALIDATION",),
    ),
    _factor(
        "ACCOUNT_RISK_STATE",
        "Account equity, contract specification, and configured risk limits",
        "EXECUTION_RISK",
        7,
        "OBSERVED",
        "CONTRACT",
        True,
        "BROKER_OR_MANUAL_ACCOUNT_STATE",
        note=(
            "No position size may be presented as known until account equity, "
            "contract size, currency conversion, and risk limits are available."
        ),
    ),
    _factor(
        "RISK_BASED_POSITION_SIZE",
        "Risk-based position size",
        "EXECUTION_RISK",
        7,
        "CALCULATED",
        "CONTRACT",
        True,
        "RISK_ENGINE",
        dependencies=("LOGICAL_STOP_DISTANCE", "ACCOUNT_RISK_STATE"),
    ),
    _factor(
        "TARGET_REWARD_RISK",
        "Target zones and reward-to-risk",
        "EXECUTION_RISK",
        7,
        "CALCULATED",
        "PARTIAL",
        True,
        "RISK_ENGINE",
        dependencies=("PRICE_INVALIDATION",),
    ),
    _factor(
        "PORTFOLIO_CLUSTER_RISK",
        "Portfolio and theme-cluster exposure",
        "EXECUTION_RISK",
        7,
        "CALCULATED",
        "CONTRACT",
        True,
        "PORTFOLIO_RISK",
        dependencies=("ACCOUNT_RISK_STATE",),
    ),
    _factor(
        "TOTAL_OPEN_RISK",
        "Total open portfolio risk",
        "EXECUTION_RISK",
        7,
        "CALCULATED",
        "CONTRACT",
        True,
        "PORTFOLIO_RISK",
        dependencies=("ACCOUNT_RISK_STATE",),
    ),
    _factor(
        "EVENT_RISK_WARNING",
        "Upcoming-event risk warning",
        "EXECUTION_RISK",
        7,
        "CALCULATED",
        "ACTIVE",
        True,
        "EVENT_CALENDAR",
        dependencies=("SCHEDULED_EVENT_CALENDAR",),
    ),
    _factor(
        "SLIPPAGE_RISK_WARNING",
        "Slippage-risk warning",
        "EXECUTION_RISK",
        7,
        "CALCULATED",
        "PARTIAL",
        True,
        "LIQUIDITY_MODEL",
        dependencies=("BID_ASK_SPREAD", "ABNORMAL_LIQUIDITY"),
    ),
    _factor(
        "DAILY_LOSS_STATUS",
        "Daily-loss status",
        "EXECUTION_RISK",
        7,
        "CALCULATED",
        "CONTRACT",
        True,
        "PORTFOLIO_RISK",
        dependencies=("ACCOUNT_RISK_STATE",),
    ),
)


FACTOR_BY_CODE = {factor.code: factor for factor in FACTOR_REGISTRY}


def registry_hash() -> str:
    payload = json.dumps(
        [asdict(factor) for factor in FACTOR_REGISTRY],
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()
